name: PR check

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
      - run: |
          for chart in charts/*/; do
            helm dependency build "$chart" 2>/dev/null || true
            helm lint "$chart"
            helm template test "$chart"
          done
